spring:
  application:
    name: agri-commerce

  profiles:
    active: local

  jackson:
    time-zone: Asia/Seoul

server:
  port: 8080

logging:
  level:
    root: info
    com.spartafarmer.agri_commerce: info  # agri_commerce 패키지는 info 레벨로 설정
