name: CD

permissions:
  contents: read

on:
  workflow_run:
    workflows: ["CI"]   # CI 워크플로우 완료 후 실행
    types:
      - completed
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # CI 성공 시에만 배포

    steps:
      # SSH로 서버 접속 & 배포
      - name: SSH로 서버 접속 & 배포
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/team1
            docker-compose -f docker-compose.prod.yml pull
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml up -d
            docker ps